query GetEpisodeById($episodeByIdId: Int!) {
  episodeById(id: $episodeByIdId) {
    rawAirTime
    airTime
    createdAt
    description
    downloadJobsByEpisodeId(orderBy: ID_DESC) {
      edges {
        node {
          createdAt
          downloadPath
          failedAt
          failedReason
          filePath
          id
          importPath
          isFailed
          nfoPath
          qbtTorrentHash
          status
          torrentLink
          jellyfinEpisodeId
          torrentTitle
        }
      }
    }
    id
    index
    jellyfinEpisodeId
    seasonBySeasonId {
      id
      title
      downloadOffsetHours
    }
    title
  }
}

mutation RetryJobStep($jobId: Int!) {
  retryJobStep(jobId: $jobId)
}

query GetActiveDownloadJobStatus($jobIds: [Int!]!) {
  getActiveDownloadJobStatus(jobIds: $jobIds) {
    downloaded
    eta
    id
    peers
    speed
    total
  }
}
