# window #0 (backend):
# |--------+--------+--------|
# |  api-  |  gate- | shell  |
# | server |  way   | (api-  |
# |        |        | server)|
# |--------+--------+--------|

# window #1 (frontend):
# |--------+--------+--------|
# | admin  | admin  | shell  |
# | (umi)  | (code- | (admin)|
# |        | gen)   |        |
# |--------+--------+--------|

# window #2 (other):
# |-------------+-------------|
# |      db     |    docs     |
# |-------------+-------------|
# |   gateway   | data-server |
# |-------------+-------------|

new-session -s 'lani dev environment' -c apps/api-server -n backend 'rushx start:dev'

set -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix
set -g pane-border-status top
set -g pane-border-format "#[fg=black, bg=green] #{pane_index} #{@custom_pane_title} "
set -g remain-on-exit
set -g mouse on

set -p @custom_pane_title 'api-server'
splitw -h -c ../gateway 'rushx dev'
set -p @custom_pane_title 'gateway'
splitw -h -c ../api-server
set -p @custom_pane_title 'shell (api-server)'
selectl even-horizontal

neww -t 1 -n frontend -c ../admin 'rushx dev:umi'
set -p @custom_pane_title 'admin (umi)'
splitw -h -c ../admin 'rushx dev:codegen'
set -p @custom_pane_title 'admin (codegen)'
splitw -h -c ../admin
set -p @custom_pane_title 'shell (admin)'
selectl even-horizontal

neww -t 2 -n other -c ../../libs/db
set -p @custom_pane_title 'shell (db)'
splitw -h -c ../../docs
set -p @custom_pane_title 'shell (docs)'
splitw -v -t 0 -c ../gateway
set -p @custom_pane_title 'shell (gateway)'
splitw -v -t 2 -c ../data-server
set -p @custom_pane_title 'shell (data-server)'

selectw -t backend