/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { Avatar } from './models/Avatar';
export { BloodType } from './models/BloodType';
export type { CharacterDetail } from './models/CharacterDetail';
export type { CharacterPerson } from './models/CharacterPerson';
export type { CharacterRevision } from './models/CharacterRevision';
export type { CharacterRevisionDataItem } from './models/CharacterRevisionDataItem';
export { CharacterType } from './models/CharacterType';
export type { Creator } from './models/Creator';
export type { DetailedRevision } from './models/DetailedRevision';
export type { Episode } from './models/Episode';
export { EpisodeCollectionType } from './models/EpisodeCollectionType';
export type { EpisodeDetail } from './models/EpisodeDetail';
export { EpType } from './models/EpType';
export type { ErrorDetail } from './models/ErrorDetail';
export type { Images } from './models/Images';
export type { Index } from './models/Index';
export type { IndexBasicInfo } from './models/IndexBasicInfo';
export type { IndexSubject } from './models/IndexSubject';
export type { IndexSubjectAddInfo } from './models/IndexSubjectAddInfo';
export type { IndexSubjectEditInfo } from './models/IndexSubjectEditInfo';
export type { Legacy_Blog } from './models/Legacy_Blog';
export type { Legacy_Character } from './models/Legacy_Character';
export { Legacy_Episode } from './models/Legacy_Episode';
export { Legacy_EpisodeType } from './models/Legacy_EpisodeType';
export type { Legacy_Mono } from './models/Legacy_Mono';
export type { Legacy_MonoBase } from './models/Legacy_MonoBase';
export type { Legacy_MonoInfo } from './models/Legacy_MonoInfo';
export type { Legacy_Person } from './models/Legacy_Person';
export type { Legacy_SubjectLarge } from './models/Legacy_SubjectLarge';
export type { Legacy_SubjectMedium } from './models/Legacy_SubjectMedium';
export { Legacy_SubjectSmall } from './models/Legacy_SubjectSmall';
export { Legacy_SubjectType } from './models/Legacy_SubjectType';
export type { Legacy_Topic } from './models/Legacy_Topic';
export type { Legacy_User } from './models/Legacy_User';
export { Legacy_UserGroup } from './models/Legacy_UserGroup';
export type { Page } from './models/Page';
export type { Paged_Episode } from './models/Paged_Episode';
export type { Paged_IndexSubject } from './models/Paged_IndexSubject';
export type { Paged_Revision } from './models/Paged_Revision';
export type { Paged_UserCollection } from './models/Paged_UserCollection';
export type { Person } from './models/Person';
export { PersonCareer } from './models/PersonCareer';
export type { PersonCharacter } from './models/PersonCharacter';
export type { PersonDetail } from './models/PersonDetail';
export type { PersonImages } from './models/PersonImages';
export type { PersonRevision } from './models/PersonRevision';
export type { PersonRevisionDataItem } from './models/PersonRevisionDataItem';
export type { PersonRevisionProfession } from './models/PersonRevisionProfession';
export { PersonType } from './models/PersonType';
export type { RelatedCharacter } from './models/RelatedCharacter';
export type { RelatedPerson } from './models/RelatedPerson';
export type { Revision } from './models/Revision';
export type { RevisionExtra } from './models/RevisionExtra';
export type { SlimSubject } from './models/SlimSubject';
export type { Stat } from './models/Stat';
export type { Subject } from './models/Subject';
export { SubjectCollectionType } from './models/SubjectCollectionType';
export type { SubjectID } from './models/SubjectID';
export type { SubjectRevision } from './models/SubjectRevision';
export type { SubjectRevisionData } from './models/SubjectRevisionData';
export type { SubjectTags } from './models/SubjectTags';
export { SubjectType } from './models/SubjectType';
export type { User } from './models/User';
export type { UserEpisodeCollection } from './models/UserEpisodeCollection';
export { UserGroup } from './models/UserGroup';
export type { UserSubjectCollection } from './models/UserSubjectCollection';
export type { v0_RelatedSubject } from './models/v0_RelatedSubject';
export type { v0_subject_relation } from './models/v0_subject_relation';
export type { WikiV0 } from './models/WikiV0';

export { BangumiAPIService } from './services/BangumiAPIService';
