apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: lani-internal-vs
  namespace: lani-offline
  labels:
    app: lani
spec:
  gateways:
  - istio-system/internal-gateway
  hosts:
  - lani.i.std4453.com
  http:

  - match:
    - uri: 
        prefix: /api/gateway
    rewrite:
      uri: /
    route:
    - destination:
        host: gateway
        port:
          number: 8080
  
  - route:
    - destination:
        host: admin
        port:
          number: 8080
