apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # basic
  - namespace.yaml
  - regcred.yaml
  - lani-cd.yaml
  # services
  # - bilibili-bangumi-cc.yaml
  # - mikan-fetch.yaml
  - data-server.yaml
  # - rss-items.yaml
  # - rss.yaml
  # - sonarr-sync.yaml
  # jobs
  # - mikan-sync.yaml
  # istio
  - istio-vs.yaml
