apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: lani
  name: lani-cd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lani-cd
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - patch
  - update
  - delete
- apiGroups: [""]
  resources:
  - services
  verbs:
  - create
  - get
  - patch
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lani-cd
  namespace: lani
subjects:
- kind: ServiceAccount
  name: lani-cd
  namespace: lani
roleRef:
  kind: ClusterRole
  name: lani-cd
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lani-cd
  namespace: lani-offline
subjects:
- kind: ServiceAccount
  name: lani-cd
  namespace: lani
roleRef:
  kind: ClusterRole
  name: lani-cd
  apiGroup: rbac.authorization.k8s.io
