apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-lani-offline
  namespace: flux-system
spec:
  interval: 5m
  releaseName: redis
  chart:
    spec:
      chart: redis
      version: 16.5.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  test:
    enable: true
  values:
    global:
      storageClass: local-path
      redis:
        password: Hd75x0NJNblIC9o9pSalT5x9KXr5Hamg
    architecture: standalone
  targetNamespace: lani-offline
