apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-pvc
  namespace: lani-offline
spec:
  resources:
    requests:
      storage: 400Gi
  volumeMode: Filesystem
  volumeName: downloads-pv
  accessModes:
    - ReadWriteMany
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: lani-offline
spec:
  resources:
    requests:
      storage: 5Ti
  volumeMode: Filesystem
  volumeName: media-pv
  accessModes:
    - ReadWriteMany
  storageClassName: ""