apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-pvc
  namespace: lani-offline
spec:
  resources:
    requests:
      storage: 400Gi
  volumeMode: Filesystem
  volumeName: lani-downloads-pv
  accessModes:
    - ReadWriteMany
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: lani-offline
spec:
  resources:
    requests:
      storage: 5Ti
  volumeMode: Filesystem
  volumeName: lani-media-pv
  accessModes:
    - ReadWriteMany
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lani-downloads-pv
spec:
  capacity:
    storage: 400Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data/std4453/services/media/downloads
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - home
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lani-media-pv
spec:
  capacity:
    storage: 5Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data/std4453/services/media/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - home