# 在本地开发时，复制本文件到 config.yaml，在 config.yaml 中填充内容

# subgraph，应当指向 data 和 api
subgraphs:
  - name: data
    url: http://data-server:8080/graphql
  - name: api
    url: http://api-server:8080/graphql

# 自动刷新间隔，不填则不会自动刷新，建议只在开发环境启用自动刷新
pollIntervalInMs: 3000

# 接入 OIDC 认证，满足条件的请求才允许执行（introspection请求除外）
auth:
  enabled: true
  issuer: https://your_oidc_issuer
  audience: <your_audience>
  role: <your_role>
# 或者使用下面的配置取消鉴权功能
# auth:
#   enabled: false