/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { Avatar } from './models/Avatar';
export { BloodType } from './models/BloodType';
export type { CharacterDetail } from './models/CharacterDetail';
export type { CharacterPerson } from './models/CharacterPerson';
export { CharacterType } from './models/CharacterType';
export type { Collection } from './models/Collection';
export type { CollectionStatus } from './models/CollectionStatus';
export { CollectionStatusId } from './models/CollectionStatusId';
export { CollectionStatusName } from './models/CollectionStatusName';
export { CollectionStatusType } from './models/CollectionStatusType';
export { CollectionType } from './models/CollectionType';
export type { Creator } from './models/Creator';
export type { DetailedRevision } from './models/DetailedRevision';
export type { Episode } from './models/Episode';
export type { EpisodeDetail } from './models/EpisodeDetail';
export { EpStatusId } from './models/EpStatusId';
export { EpStatusName } from './models/EpStatusName';
export { EpStatusType } from './models/EpStatusType';
export { EpType } from './models/EpType';
export type { ErrorDetail } from './models/ErrorDetail';
export type { Images } from './models/Images';
export type { Index } from './models/Index';
export type { IndexSubject } from './models/IndexSubject';
export type { Item } from './models/Item';
export type { KV } from './models/KV';
export type { Me } from './models/Me';
export type { Paged_Episode_ } from './models/Paged_Episode_';
export type { Paged_IndexSubject_ } from './models/Paged_IndexSubject_';
export type { Paged_Revision_ } from './models/Paged_Revision_';
export type { Paged_UserCollection_ } from './models/Paged_UserCollection_';
export type { Person } from './models/Person';
export { PersonCareer } from './models/PersonCareer';
export type { PersonCharacter } from './models/PersonCharacter';
export type { PersonDetail } from './models/PersonDetail';
export type { PersonImages } from './models/PersonImages';
export type { PersonRevision } from './models/PersonRevision';
export type { PersonRevisionDataItem } from './models/PersonRevisionDataItem';
export type { PersonRevisionExtra } from './models/PersonRevisionExtra';
export type { PersonRevisionProfession } from './models/PersonRevisionProfession';
export { PersonType } from './models/PersonType';
export type { pol__api__v0__models__RelatedSubject } from './models/pol__api__v0__models__RelatedSubject';
export type { pol__api__v0__models__subject__RelatedSubject } from './models/pol__api__v0__models__subject__RelatedSubject';
export type { Rating } from './models/Rating';
export type { RelatedCharacter } from './models/RelatedCharacter';
export type { RelatedPerson } from './models/RelatedPerson';
export { ResponseGroup } from './models/ResponseGroup';
export type { Revision } from './models/Revision';
export type { Stat } from './models/Stat';
export { StatusCode } from './models/StatusCode';
export type { Subject } from './models/Subject';
export type { Subject1 } from './models/Subject1';
export type { SubjectBase } from './models/SubjectBase';
export type { SubjectCollection } from './models/SubjectCollection';
export type { SubjectSmall } from './models/SubjectSmall';
export { SubjectType } from './models/SubjectType';
export { SubjectType1 } from './models/SubjectType1';
export { SubjectTypeName } from './models/SubjectTypeName';
export type { Tag } from './models/Tag';
export type { User } from './models/User';
export type { UserCollection } from './models/UserCollection';
export { UserGroup } from './models/UserGroup';
export { UserGroup1 } from './models/UserGroup1';
export type { V } from './models/V';
export type { ValidationError } from './models/ValidationError';

export { BangumiAPIService } from './services/BangumiAPIService';
