/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AccessSchedule } from './models/AccessSchedule';
export type { ActivityLogEntry } from './models/ActivityLogEntry';
export type { ActivityLogEntryQueryResult } from './models/ActivityLogEntryQueryResult';
export type { AddVirtualFolderDto } from './models/AddVirtualFolderDto';
export type { AdminNotificationDto } from './models/AdminNotificationDto';
export type { AlbumInfo } from './models/AlbumInfo';
export type { AlbumInfoRemoteSearchQuery } from './models/AlbumInfoRemoteSearchQuery';
export type { AllThemeMediaResult } from './models/AllThemeMediaResult';
export { Architecture } from './models/Architecture';
export type { ArtistInfo } from './models/ArtistInfo';
export type { ArtistInfoRemoteSearchQuery } from './models/ArtistInfoRemoteSearchQuery';
export type { AuthenticateUserByName } from './models/AuthenticateUserByName';
export type { AuthenticationInfo } from './models/AuthenticationInfo';
export type { AuthenticationInfoQueryResult } from './models/AuthenticationInfoQueryResult';
export type { AuthenticationResult } from './models/AuthenticationResult';
export type { BaseItem } from './models/BaseItem';
export type { BaseItemDto } from './models/BaseItemDto';
export type { BaseItemDtoQueryResult } from './models/BaseItemDtoQueryResult';
export type { BaseItemPerson } from './models/BaseItemPerson';
export type { BasePluginConfiguration } from './models/BasePluginConfiguration';
export type { BookInfo } from './models/BookInfo';
export type { BookInfoRemoteSearchQuery } from './models/BookInfoRemoteSearchQuery';
export type { BoxSetInfo } from './models/BoxSetInfo';
export type { BoxSetInfoRemoteSearchQuery } from './models/BoxSetInfoRemoteSearchQuery';
export type { BrandingOptions } from './models/BrandingOptions';
export type { BufferRequestDto } from './models/BufferRequestDto';
export type { ChannelFeatures } from './models/ChannelFeatures';
export { ChannelItemSortField } from './models/ChannelItemSortField';
export type { ChannelMappingOptionsDto } from './models/ChannelMappingOptionsDto';
export { ChannelMediaContentType } from './models/ChannelMediaContentType';
export { ChannelMediaType } from './models/ChannelMediaType';
export { ChannelType } from './models/ChannelType';
export type { ChapterInfo } from './models/ChapterInfo';
export type { ClientCapabilities } from './models/ClientCapabilities';
export type { ClientCapabilitiesDto } from './models/ClientCapabilitiesDto';
export type { CodecProfile } from './models/CodecProfile';
export { CodecType } from './models/CodecType';
export type { CollectionCreationResult } from './models/CollectionCreationResult';
export { CollectionTypeOptions } from './models/CollectionTypeOptions';
export type { ConfigurationPageInfo } from './models/ConfigurationPageInfo';
export { ConfigurationPageType } from './models/ConfigurationPageType';
export type { ContainerProfile } from './models/ContainerProfile';
export type { ControlResponse } from './models/ControlResponse';
export type { CountryInfo } from './models/CountryInfo';
export type { CreatePlaylistDto } from './models/CreatePlaylistDto';
export type { CreateUserByName } from './models/CreateUserByName';
export type { CultureDto } from './models/CultureDto';
export { DayOfWeek } from './models/DayOfWeek';
export { DayPattern } from './models/DayPattern';
export type { DefaultDirectoryBrowserInfoDto } from './models/DefaultDirectoryBrowserInfoDto';
export type { DeviceIdentification } from './models/DeviceIdentification';
export type { DeviceInfo } from './models/DeviceInfo';
export type { DeviceInfoQueryResult } from './models/DeviceInfoQueryResult';
export type { DeviceOptions } from './models/DeviceOptions';
export type { DeviceProfile } from './models/DeviceProfile';
export type { DeviceProfileInfo } from './models/DeviceProfileInfo';
export { DeviceProfileType } from './models/DeviceProfileType';
export type { DirectPlayProfile } from './models/DirectPlayProfile';
export type { DisplayPreferencesDto } from './models/DisplayPreferencesDto';
export { DlnaProfileType } from './models/DlnaProfileType';
export { DynamicDayOfWeek } from './models/DynamicDayOfWeek';
export { EncodingContext } from './models/EncodingContext';
export type { EndPointInfo } from './models/EndPointInfo';
export type { ExternalIdInfo } from './models/ExternalIdInfo';
export { ExternalIdMediaType } from './models/ExternalIdMediaType';
export type { ExternalUrl } from './models/ExternalUrl';
export { FFmpegLocation } from './models/FFmpegLocation';
export type { FileSystemEntryInfo } from './models/FileSystemEntryInfo';
export { FileSystemEntryType } from './models/FileSystemEntryType';
export type { FontFile } from './models/FontFile';
export { ForgotPasswordAction } from './models/ForgotPasswordAction';
export type { ForgotPasswordDto } from './models/ForgotPasswordDto';
export type { ForgotPasswordPinDto } from './models/ForgotPasswordPinDto';
export type { ForgotPasswordResult } from './models/ForgotPasswordResult';
export type { GeneralCommand } from './models/GeneralCommand';
export { GeneralCommandType } from './models/GeneralCommandType';
export type { GetProgramsDto } from './models/GetProgramsDto';
export type { GroupInfoDto } from './models/GroupInfoDto';
export { GroupQueueMode } from './models/GroupQueueMode';
export { GroupRepeatMode } from './models/GroupRepeatMode';
export { GroupShuffleMode } from './models/GroupShuffleMode';
export { GroupStateType } from './models/GroupStateType';
export { GroupUpdateType } from './models/GroupUpdateType';
export type { GuideInfo } from './models/GuideInfo';
export { HeaderMatchType } from './models/HeaderMatchType';
export type { HttpHeaderInfo } from './models/HttpHeaderInfo';
export type { IgnoreWaitRequestDto } from './models/IgnoreWaitRequestDto';
export type { ImageByNameInfo } from './models/ImageByNameInfo';
export { ImageFormat } from './models/ImageFormat';
export type { ImageInfo } from './models/ImageInfo';
export type { ImageOption } from './models/ImageOption';
export { ImageOrientation } from './models/ImageOrientation';
export type { ImageProviderInfo } from './models/ImageProviderInfo';
export { ImageSavingConvention } from './models/ImageSavingConvention';
export { ImageType } from './models/ImageType';
export type { InstallationInfo } from './models/InstallationInfo';
export type { IPlugin } from './models/IPlugin';
export { IsoType } from './models/IsoType';
export type { ItemCounts } from './models/ItemCounts';
export { ItemFields } from './models/ItemFields';
export { ItemFilter } from './models/ItemFilter';
export type { JoinGroupRequestDto } from './models/JoinGroupRequestDto';
export { KeepUntil } from './models/KeepUntil';
export type { LibraryOptionInfoDto } from './models/LibraryOptionInfoDto';
export type { LibraryOptions } from './models/LibraryOptions';
export type { LibraryOptionsResultDto } from './models/LibraryOptionsResultDto';
export type { LibraryTypeOptionsDto } from './models/LibraryTypeOptionsDto';
export type { LibraryUpdateInfo } from './models/LibraryUpdateInfo';
export type { ListingsProviderInfo } from './models/ListingsProviderInfo';
export type { LiveStreamResponse } from './models/LiveStreamResponse';
export type { LiveTvInfo } from './models/LiveTvInfo';
export type { LiveTvServiceInfo } from './models/LiveTvServiceInfo';
export { LiveTvServiceStatus } from './models/LiveTvServiceStatus';
export type { LocalizationOption } from './models/LocalizationOption';
export { LocationType } from './models/LocationType';
export type { LogFile } from './models/LogFile';
export { LogLevel } from './models/LogLevel';
export type { MediaAttachment } from './models/MediaAttachment';
export type { MediaEncoderPathDto } from './models/MediaEncoderPathDto';
export type { MediaPathDto } from './models/MediaPathDto';
export type { MediaPathInfo } from './models/MediaPathInfo';
export { MediaProtocol } from './models/MediaProtocol';
export type { MediaSourceInfo } from './models/MediaSourceInfo';
export { MediaSourceType } from './models/MediaSourceType';
export type { MediaStream } from './models/MediaStream';
export { MediaStreamType } from './models/MediaStreamType';
export type { MediaUpdateInfoDto } from './models/MediaUpdateInfoDto';
export type { MediaUpdateInfoPathDto } from './models/MediaUpdateInfoPathDto';
export type { MediaUrl } from './models/MediaUrl';
export type { MessageCommand } from './models/MessageCommand';
export type { MetadataEditorInfo } from './models/MetadataEditorInfo';
export { MetadataField } from './models/MetadataField';
export type { MetadataOptions } from './models/MetadataOptions';
export { MetadataRefreshMode } from './models/MetadataRefreshMode';
export type { MovePlaylistItemRequestDto } from './models/MovePlaylistItemRequestDto';
export type { MovieInfo } from './models/MovieInfo';
export type { MovieInfoRemoteSearchQuery } from './models/MovieInfoRemoteSearchQuery';
export type { MusicVideoInfo } from './models/MusicVideoInfo';
export type { MusicVideoInfoRemoteSearchQuery } from './models/MusicVideoInfoRemoteSearchQuery';
export type { NameGuidPair } from './models/NameGuidPair';
export type { NameIdPair } from './models/NameIdPair';
export type { NameValuePair } from './models/NameValuePair';
export type { NewGroupRequestDto } from './models/NewGroupRequestDto';
export type { NextItemRequestDto } from './models/NextItemRequestDto';
export type { NotificationDto } from './models/NotificationDto';
export { NotificationLevel } from './models/NotificationLevel';
export type { NotificationResultDto } from './models/NotificationResultDto';
export type { NotificationsSummaryDto } from './models/NotificationsSummaryDto';
export type { NotificationTypeInfo } from './models/NotificationTypeInfo';
export type { ObjectGroupUpdate } from './models/ObjectGroupUpdate';
export type { OpenLiveStreamDto } from './models/OpenLiveStreamDto';
export type { PackageInfo } from './models/PackageInfo';
export type { ParentalRating } from './models/ParentalRating';
export type { PathSubstitution } from './models/PathSubstitution';
export type { PersonLookupInfo } from './models/PersonLookupInfo';
export type { PersonLookupInfoRemoteSearchQuery } from './models/PersonLookupInfoRemoteSearchQuery';
export type { PingRequestDto } from './models/PingRequestDto';
export type { PinRedeemResult } from './models/PinRedeemResult';
export { PlayAccess } from './models/PlayAccess';
export { PlaybackErrorCode } from './models/PlaybackErrorCode';
export type { PlaybackInfoDto } from './models/PlaybackInfoDto';
export type { PlaybackInfoResponse } from './models/PlaybackInfoResponse';
export type { PlaybackProgressInfo } from './models/PlaybackProgressInfo';
export type { PlaybackStartInfo } from './models/PlaybackStartInfo';
export type { PlaybackStopInfo } from './models/PlaybackStopInfo';
export { PlayCommand } from './models/PlayCommand';
export type { PlayerStateInfo } from './models/PlayerStateInfo';
export type { PlaylistCreationResult } from './models/PlaylistCreationResult';
export { PlayMethod } from './models/PlayMethod';
export type { PlayRequest } from './models/PlayRequest';
export type { PlayRequestDto } from './models/PlayRequestDto';
export { PlaystateCommand } from './models/PlaystateCommand';
export type { PlaystateRequest } from './models/PlaystateRequest';
export type { PluginInfo } from './models/PluginInfo';
export type { PluginSecurityInfo } from './models/PluginSecurityInfo';
export { PluginStatus } from './models/PluginStatus';
export type { PreviousItemRequestDto } from './models/PreviousItemRequestDto';
export type { ProblemDetails } from './models/ProblemDetails';
export type { ProfileCondition } from './models/ProfileCondition';
export { ProfileConditionType } from './models/ProfileConditionType';
export { ProfileConditionValue } from './models/ProfileConditionValue';
export { ProgramAudio } from './models/ProgramAudio';
export type { PublicSystemInfo } from './models/PublicSystemInfo';
export type { QueryFilters } from './models/QueryFilters';
export type { QueryFiltersLegacy } from './models/QueryFiltersLegacy';
export type { QueueItem } from './models/QueueItem';
export type { QueueRequestDto } from './models/QueueRequestDto';
export type { QuickConnectDto } from './models/QuickConnectDto';
export type { QuickConnectResult } from './models/QuickConnectResult';
export { QuickConnectState } from './models/QuickConnectState';
export { RatingType } from './models/RatingType';
export type { ReadyRequestDto } from './models/ReadyRequestDto';
export type { RecommendationDto } from './models/RecommendationDto';
export { RecommendationType } from './models/RecommendationType';
export { RecordingStatus } from './models/RecordingStatus';
export type { RemoteImageInfo } from './models/RemoteImageInfo';
export type { RemoteImageResult } from './models/RemoteImageResult';
export type { RemoteSearchResult } from './models/RemoteSearchResult';
export type { RemoteSubtitleInfo } from './models/RemoteSubtitleInfo';
export type { RemoveFromPlaylistRequestDto } from './models/RemoveFromPlaylistRequestDto';
export { RepeatMode } from './models/RepeatMode';
export type { RepositoryInfo } from './models/RepositoryInfo';
export type { ResponseProfile } from './models/ResponseProfile';
export { ScrollDirection } from './models/ScrollDirection';
export type { SearchHint } from './models/SearchHint';
export type { SearchHintResult } from './models/SearchHintResult';
export type { SeekRequestDto } from './models/SeekRequestDto';
export type { SendCommand } from './models/SendCommand';
export { SendCommandType } from './models/SendCommandType';
export type { SeriesInfo } from './models/SeriesInfo';
export type { SeriesInfoRemoteSearchQuery } from './models/SeriesInfoRemoteSearchQuery';
export { SeriesStatus } from './models/SeriesStatus';
export type { SeriesTimerInfoDto } from './models/SeriesTimerInfoDto';
export type { SeriesTimerInfoDtoQueryResult } from './models/SeriesTimerInfoDtoQueryResult';
export type { ServerConfiguration } from './models/ServerConfiguration';
export type { ServerDiscoveryInfo } from './models/ServerDiscoveryInfo';
export type { SessionInfo } from './models/SessionInfo';
export { SessionMessageType } from './models/SessionMessageType';
export type { SessionUserInfo } from './models/SessionUserInfo';
export type { SetChannelMappingDto } from './models/SetChannelMappingDto';
export type { SetPlaylistItemRequestDto } from './models/SetPlaylistItemRequestDto';
export type { SetRepeatModeRequestDto } from './models/SetRepeatModeRequestDto';
export type { SetShuffleModeRequestDto } from './models/SetShuffleModeRequestDto';
export type { SongInfo } from './models/SongInfo';
export { SortOrder } from './models/SortOrder';
export type { SpecialViewOptionDto } from './models/SpecialViewOptionDto';
export type { StartupConfigurationDto } from './models/StartupConfigurationDto';
export type { StartupRemoteAccessDto } from './models/StartupRemoteAccessDto';
export type { StartupUserDto } from './models/StartupUserDto';
export { SubtitleDeliveryMethod } from './models/SubtitleDeliveryMethod';
export { SubtitlePlaybackMode } from './models/SubtitlePlaybackMode';
export type { SubtitleProfile } from './models/SubtitleProfile';
export { SyncPlayUserAccessType } from './models/SyncPlayUserAccessType';
export type { SystemInfo } from './models/SystemInfo';
export { TaskCompletionStatus } from './models/TaskCompletionStatus';
export type { TaskInfo } from './models/TaskInfo';
export type { TaskResult } from './models/TaskResult';
export { TaskState } from './models/TaskState';
export type { TaskTriggerInfo } from './models/TaskTriggerInfo';
export type { ThemeMediaResult } from './models/ThemeMediaResult';
export type { TimerEventInfo } from './models/TimerEventInfo';
export type { TimerInfoDto } from './models/TimerInfoDto';
export type { TimerInfoDtoQueryResult } from './models/TimerInfoDtoQueryResult';
export type { TrailerInfo } from './models/TrailerInfo';
export type { TrailerInfoRemoteSearchQuery } from './models/TrailerInfoRemoteSearchQuery';
export { TranscodeReason } from './models/TranscodeReason';
export { TranscodeSeekInfo } from './models/TranscodeSeekInfo';
export type { TranscodingInfo } from './models/TranscodingInfo';
export type { TranscodingProfile } from './models/TranscodingProfile';
export { TransportStreamTimestamp } from './models/TransportStreamTimestamp';
export type { TunerChannelMapping } from './models/TunerChannelMapping';
export type { TunerHostInfo } from './models/TunerHostInfo';
export type { TypeOptions } from './models/TypeOptions';
export { UnratedItem } from './models/UnratedItem';
export type { UpdateLibraryOptionsDto } from './models/UpdateLibraryOptionsDto';
export type { UpdateMediaPathRequestDto } from './models/UpdateMediaPathRequestDto';
export type { UpdateUserEasyPassword } from './models/UpdateUserEasyPassword';
export type { UpdateUserPassword } from './models/UpdateUserPassword';
export type { UploadSubtitleDto } from './models/UploadSubtitleDto';
export type { UserConfiguration } from './models/UserConfiguration';
export type { UserDto } from './models/UserDto';
export type { UserItemDataDto } from './models/UserItemDataDto';
export type { UserPolicy } from './models/UserPolicy';
export type { UtcTimeResponse } from './models/UtcTimeResponse';
export type { ValidatePathDto } from './models/ValidatePathDto';
export type { Version } from './models/Version';
export type { VersionInfo } from './models/VersionInfo';
export { Video3DFormat } from './models/Video3DFormat';
export { VideoType } from './models/VideoType';
export type { VirtualFolderInfo } from './models/VirtualFolderInfo';
export type { WakeOnLanInfo } from './models/WakeOnLanInfo';
export type { XmlAttribute } from './models/XmlAttribute';

export { ActivityLogService } from './services/ActivityLogService';
export { ApiKeyService } from './services/ApiKeyService';
export { ArtistsService } from './services/ArtistsService';
export { AudioService } from './services/AudioService';
export { BrandingService } from './services/BrandingService';
export { ChannelsService } from './services/ChannelsService';
export { CollectionService } from './services/CollectionService';
export { ConfigurationService } from './services/ConfigurationService';
export { DashboardService } from './services/DashboardService';
export { DevicesService } from './services/DevicesService';
export { DisplayPreferencesService } from './services/DisplayPreferencesService';
export { DlnaService } from './services/DlnaService';
export { DlnaServerService } from './services/DlnaServerService';
export { DynamicHlsService } from './services/DynamicHlsService';
export { EnvironmentService } from './services/EnvironmentService';
export { FilterService } from './services/FilterService';
export { GenresService } from './services/GenresService';
export { HlsSegmentService } from './services/HlsSegmentService';
export { ImageService } from './services/ImageService';
export { ImageByNameService } from './services/ImageByNameService';
export { InstantMixService } from './services/InstantMixService';
export { ItemLookupService } from './services/ItemLookupService';
export { ItemRefreshService } from './services/ItemRefreshService';
export { ItemsService } from './services/ItemsService';
export { ItemUpdateService } from './services/ItemUpdateService';
export { LibraryService } from './services/LibraryService';
export { LibraryStructureService } from './services/LibraryStructureService';
export { LiveTvService } from './services/LiveTvService';
export { LocalizationService } from './services/LocalizationService';
export { MediaInfoService } from './services/MediaInfoService';
export { MoviesService } from './services/MoviesService';
export { MusicGenresService } from './services/MusicGenresService';
export { NotificationsService } from './services/NotificationsService';
export { PackageService } from './services/PackageService';
export { PersonsService } from './services/PersonsService';
export { PlaylistsService } from './services/PlaylistsService';
export { PlaystateService } from './services/PlaystateService';
export { PluginsService } from './services/PluginsService';
export { QuickConnectService } from './services/QuickConnectService';
export { RemoteImageService } from './services/RemoteImageService';
export { ScheduledTasksService } from './services/ScheduledTasksService';
export { SearchService } from './services/SearchService';
export { SessionService } from './services/SessionService';
export { StartupService } from './services/StartupService';
export { StudiosService } from './services/StudiosService';
export { SubtitleService } from './services/SubtitleService';
export { SuggestionsService } from './services/SuggestionsService';
export { SyncPlayService } from './services/SyncPlayService';
export { SystemService } from './services/SystemService';
export { TimeSyncService } from './services/TimeSyncService';
export { TrailersService } from './services/TrailersService';
export { TvShowsService } from './services/TvShowsService';
export { UniversalAudioService } from './services/UniversalAudioService';
export { UserService } from './services/UserService';
export { UserLibraryService } from './services/UserLibraryService';
export { UserViewsService } from './services/UserViewsService';
export { VideoAttachmentsService } from './services/VideoAttachmentsService';
export { VideoHlsService } from './services/VideoHlsService';
export { VideosService } from './services/VideosService';
export { YearsService } from './services/YearsService';
