// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'breadcrumbContainer': string;
  'directory': string;
  'header': string;
  'import': string;
  'importAlert': string;
  'importList': string;
  'importModal': string;
  'importSelect': string;
  'modal': string;
  'row': string;
  'search': string;
  'selected': string;
  'settings': string;
  'table': string;
  'tableContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
