name: "@lani/all-in-one Pipeline"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Ref to trigger workflow"
        required: false
        default: "master"
      project_name:
        description: "Project package name"
        required: true
  
permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build_generic.yaml
    with:
      ref: ${{ inputs.ref }}
      project_name: ${{ inputs.project_name }}
    secrets: inherit
  