name: "Default Node.js CI"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Ref to trigger workflow"
        required: false
        default: "master"
      image_name:
        description: "Image name"
        required: true
      image_owner: 
        description: "Image owner"
        required: false
        default: "std4453"
      project_name:
        description: "Project package name"
        required: true
      project_path:
        description: "Project path"
        required: true
      deploy_name:
        description: "k8s deployment name"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          ref: ${{ github.event.inputs.ref }}

      - uses: docker/setup-buildx-action@v1
        name: Setup Docker Buildx

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: '14'

      # https://github.com/microsoft/rushstack/issues/1847#issuecomment-993825253

      - name: Cache Rush
        uses: actions/cache@v2
        with:
          path: |
            common/temp/install-run
          key: ${{ runner.os }}-${{ hashFiles('rush.json') }}

      - name: Cache pnpm
        uses: actions/cache@v2
        with:
          path: |
            common/temp/pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      
      - name: Install Dependencies
        run: |
          node common/scripts/install-run-rush.js install --no-link
        
      - name: Link Dependencies
        run: |
          node common/scripts/install-run-rush.js link
      
      - name: Build
        run: |
          node common/scripts/install-run-rush.js build -t ${{ github.event.inputs.project_name }} -p 1 -v
       
      - name: Deploy
        run: |
          node common/scripts/install-run-rush.js deploy -p ${{ github.event.inputs.project_name }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./${{ github.event.inputs.project_path }}/Dockerfile
          tags: >
            ghcr.io/${{ github.event.inputs.image_owner }}/${{ github.event.inputs.image_name }}:latest,
            ghcr.io/${{ github.event.inputs.image_owner }}/${{ github.event.inputs.image_name }}:1.0.${{ github.run_number }},
            ghcr.io/${{ github.event.inputs.image_owner }}/${{ github.event.inputs.image_name }}:${{ github.sha }},
            ghcr.io/${{ github.event.inputs.image_owner }}/${{ github.event.inputs.image_name }}:${{ github.event.inputs.ref }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.inputs.deploy_name != null
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Prepare kubeconfig
        run: |
          echo "KUBE_CONFIG=$(cat deploy/kust/lani-cd.kubeconfig | base64 -w 0)" >> $GITHUB_ENV

      - uses: actions-hub/kubectl@master
        name: Rollout
        env:
          KUBE_CONFIG: ${{ env.KUBE_CONFIG }}
        with:
          args: rollout restart deployment/${{ github.event.inputs.deploy_name }}
